/*Generate Valid Angle Bracket Sequences
Given n, return all valid sequences of n pairs of '<' and '>' with proper nesting.

Examples
Example 1

Input:

n = 1
Output:

<>
Explanation:

With one pair of angle brackets, the only valid nesting is "< >".
The function starts with an empty string and can only place a '<' then a '>' yielding "<>".
Example 2

Input:

n = 2
Output:

<><>
<<>>
Explanation:

There are two valid sequences for two pairs:
"<><>" — place the two pairs side by side.
"<<>>" — nest the second pair inside the first.
The backtracking builds these by adding '<' when we have not yet placed 2, and '>' when there is an unmatched '<'.
Example 3

Input:

n = 3
Output:

<<<>>>
<<><>>
<<>><>
<><<>>
<><><>
Explanation:

For three pairs, there are 5 valid sequences (analogous to balanced parentheses):

"((()))" → "<<<>>>"
"(()())" → "<<><>>"
"(())()" → "<<>><>"
"()(())" → "<><<>>"
"()()()" → "<><><>"
Each sequence is generated by choosing to place '<' when remaining > 0, and '>' when there is at least one unmatched '<'.

Input Format

The first line contains a single integer, n, representing the total number of meetings.
The next n lines each contain two space-separated integers, representing the start_time and end_time of a single meeting.
6
1 2
3 4
0 6
5 7
8 9
5 9
Explanation:

n = 6, indicating there are six meetings to process.
The subsequent six lines represent the start and end times for each meeting. For example, the first meeting starts at time 1 and ends at time 2.
Constraints

0 <= n <= 12
n is an integer
Output Format

Return a STRING_ARRAY containing every valid sequence of 2·n characters where:

Sample Input 0

1
Sample Output 0

<>
Sample Input 1

2
Sample Output 1

<<>>
<><>*/

function maximizeNonOverlappingMeetings(n) {
    // Write your code here
     const result = [];

    function backtrack(current, openCount, closeCount) {
        if (current.length === 2 * n) {
            result.push(current);
            return;
        }

        if (openCount < n) {
            backtrack(current + '<', openCount + 1, closeCount);
        }

        if (closeCount < openCount) {
            backtrack(current + '>', openCount, closeCount + 1);
        }
    }

    backtrack('', 0, 0);
    return result;
}



